### PR TITLE
Integrate Codecov

### PR DESCRIPTION
**Pull request by muzaffaryousaf**
# [EDUCATOR-974](https://openedx.atlassian.net/browse/EDUCATOR-974)
Purpose of this PR is to add these things for travis:
- Codecov
- Makefile
- Test commands
- pep8 and pylint

NOTE: pylint has been disabled for now because of hundred of issues. I've created a ticket for that https://openedx.atlassian.net/browse/EDUCATOR-977

### CODE REVIEW

**Comment by muzaffaryousaf** [comment]
```
pep8
./scripts/test_hls.py:8:19: E251 unexpected spaces around keyword / parameter equals
./scripts/test_hls.py:8:21: E251 unexpected spaces around keyword / parameter equals
./scripts/test_hls.py:9:10: E251 unexpected spaces around keyword / parameter equals
./scripts/test_hls.py:9:12: E251 unexpected spaces around keyword / parameter equals
```

**Comment by muzaffaryousaf** [comment]
Quality build is failing.

**Comment by muzaffaryousaf** [comment]
```
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```
@yro This build is not able to install ffmpeg, looks like this is due to newer version of Ubuntu on Travis Machine. Any thoughts ?

**Comment by muzaffaryousaf** [comment]
I'm getting this kind of results from Google https://askubuntu.com/questions/432542/is-ffmpeg-missing-from-the-official-repositories-in-14-04

**Comment by muzaffaryousaf** [comment]
@yro Can you give it a quick look ?

**Comment by muzaffaryousaf** [comment]
@yro Coverage is failing for now because of few tests and also because of tests being in different format which we'll be addressing soon.

**Comment by yro** [comment]
@muzaffaryousaf This looks good! 

In the past I've compiled ffmpeg from a static build, since compiling it is so time consuming. It's a sticky problem, though. I've worked on libraries, but haven't had much success.

**Comment by muzaffaryousaf** [comment]
@yro For now i sticked to the precise distribution but we've to fix this since precise dist will be deprecated in few months.

**Comment by muzaffaryousaf** [comment]
@yro Are we good to merge this PR ?

**Comment by yro** [comment]
@muzaffaryousaf Yep! Go ahead.

**Pull request merged**
