### PR TITLE
fix video images s3 key

### PR DESCRIPTION
**Pull request by muhammad-ammar**
This fixes the double `//` coming in s3 key.

### CODE REVIEW

**Comment by muzaffaryousaf** [comment]
@muhammad-ammar I think we should merge this ?

**Comment by muhammad-ammar** [comment]
@muzaffaryousaf If you think its OK then we can merge it.

**Comment by muzaffaryousaf** [comment]
@muhammad-ammar let's get @yro 's thumb and merge it.

**Comment by muzaffaryousaf** [comment]
@yro can you please give it a quick look. Also, FYI, build_url utility could be used in many places.

**Comment by yro** [comment]
@muzaffaryousaf Yeah, nice! 👍

**Comment by muzaffaryousaf** [comment]
@muhammad-ammar Let's merge this.

**Pull request merged**
