### PR TITLE
Make course ids available to update auto-generated images in edx-val.

### PR DESCRIPTION
**Pull request by muzaffaryousaf**
Filling up course_url (course_ids) for video images.

### CODE REVIEW

**Comment by Qubad786** [comment]
@muhammad-ammar , @muzaffaryousaf may you please review.

**Comment by Qubad786** [comment]
this is edx-video-pipeline part – https://github.com/edx/edx-video-pipeline/pull/9

**Comment by Qubad786** [comment]
@yro may please you take a quick look on this PR? It fixes the auto-generated video images feature.
edx-video-pipeline part – edx/edx-video-pipeline#9

**Comment by yro** [comment]
@Qubad786 This looks great! Thank you!

**Pull request merged**
